### ISSUE TITLE
Add an option to change palette shortcut

### ISSUE THREAD

**Issue by jsamr** [moosingin3space/wksp-for-firefox#1]
`Alt+space` opens the kde fast command typer in my distro!

**Comment by moosingin3space** [comment]
Oh, duh! I rebound the KDE runner to `Super+space` on my laptop, so I didn't even think about the defaults!

**Comment by jsamr** [comment]
@moosingin3space np, cool extension !

**Comment by moosingin3space** [comment]
Changing the shortcut only works in Firefox >= 60. As a result, the options page will not work in the current FF 59 stable. I'm open to suggestions for a secondary default shortcut for the next few weeks!

**Comment by MoscaDotTo** [comment]
ALT reveals / focuses the menubar on Windows (system level behavior that I'm not sure is changeable) which is also problematic. Adding a button in the arrow panel that opens the palette might be a good workaround in the interim.

**Comment by zakius** [comment]
Well, what about using ctrl+space as a secondary? seems to be available

And it's nice that it works on 56, using 60+ (or actually 57+) APIs will make it obsolete

**Comment by moosingin3space** [comment]
@zakius Ctrl+space sounds like a good choice for the secondary. Gonna look at the API one more time and add it.
I should comment though that I'm not planning on officially supporting anything other than 59+, as I only use 59 and 60 on my machines, but I will do my best to gracefully degrade if an API is not present. 

@MoscaDotTo what do you mean by "a button in the arrow panel"? Is this different than the popup button I already have in the toolbar?

**Comment by MoscaDotTo** [comment]
The popup button in the toolbar produces an arrow panel. 

https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/panel

If you placed a button inside your popup, it'd give a UI interaction that could present the palette alongside the current (unusable on Windows) keyboard shortcut. Less savvy users tend to prefer buttons over key combos too.

**Comment by moosingin3space** [comment]
@MoscaDotTo I'm not following you very well. Doesn't the toolbar button already open the palette? (If not, that's an issue, please file it separately.) Are you suggesting I display the keyboard shortcut in the popup?

Also, I think Ctrl+space is going to become the official hotkey, in order to make this usable on Windows. It will be configurable in 60+, but the extension will continue to function in older versions.

**Comment by moosingin3space** [comment]
And looks like there's a [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1408129) that makes it impossible to set two keybindings to a single command.

**Comment by moosingin3space** [comment]
I've added the options page in this commit: https://github.com/moosingin3space/wksp-for-firefox/commit/5fed1aa746eb4d6e5fe3a86f06a717c78604afe0. The preference will work on Firefox 60+.

I'm going to push the new release 1.0.4 to AMO shortly, which merges this functionality.

**Comment by moosingin3space** [comment]
Commit https://github.com/moosingin3space/wksp-for-firefox/releases/tag/v1.0.5 changes the default on Windows to `Ctrl+Space`. As a result, for the next few weeks, Windows users on the stable/release branch of Firefox can use `Ctrl+Space`. Upon the release of Firefox 60, you will be able to change the hotkey to whatever you desire, as long as it is accepted by the API. 

I'm going to consider this issue closed. Thanks for using my extension and demonstrating interest! I'm glad something I found useful myself is also useful to you.
